class AgentBootstrapConstants:
    DEEPSEEK_API_KEY_ENV = "DEEPSEEK_API_KEY"
    DEEPSEEK_MODEL_ENV = "DEEPSEEK_MODEL"
    DEEPSEEK_CONTEXT_WINDOW_TOKENS_ENV = "DEEPSEEK_CONTEXT_WINDOW_TOKENS"
    DATABASE_URL_ENV = "DATABASE_URL"
    ALLOWED_LOGIN_EMAILS_ENV = "ALLOWED_LOGIN_EMAILS"
    SMTP_HOST_ENV = "SMTP_HOST"
    SMTP_PORT_ENV = "SMTP_PORT"
    SMTP_SSL_ENV = "SMTP_SSL"
    SMTP_USER_ENV = "SMTP_USER"
    SMTP_PASSWORD_ENV = "SMTP_PASSWORD"
    MAIL_FROM_ENV = "MAIL_FROM"
    SESSION_SECRET_ENV = "SESSION_SECRET"
    DASHSCOPE_API_KEY_ENV = "DASHSCOPE_API_KEY"
    PKA_CLOUD_ONLY_ENV = "PKA_CLOUD_ONLY"
    QWEN_EMBEDDING_BASE_URL_ENV = "QWEN_EMBEDDING_BASE_URL"
    QWEN_EMBEDDING_MODEL_ENV = "QWEN_EMBEDDING_MODEL"
    QWEN_EMBEDDING_DIMENSIONS_ENV = "QWEN_EMBEDDING_DIMENSIONS"
    DEFAULT_DEEPSEEK_MODEL = "deepseek-v4-flash"
    DEFAULT_CONTEXT_WINDOW_TOKENS_BY_MODEL = {
        DEFAULT_DEEPSEEK_MODEL: 1_000_000,
    }
    DEFAULT_ALLOWED_LOGIN_EMAILS = ("1033795760@qq.com",)
    DEFAULT_QWEN_EMBEDDING_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
    DEFAULT_QWEN_EMBEDDING_MODEL = "text-embedding-v4"
    DEFAULT_QWEN_EMBEDDING_DIMENSIONS = 1024
    DEFAULT_SMTP_PORT = 465
